apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v2
  namespace: sandeep
  annotations:
    kubernetes.io/change-cause: "caddy canary version"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: c1
        image: caddy
