apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-lb
  namespace: sandeep
  annotations:
    kubernetes.io/change-cause: "initial caddy deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: c1
        image: caddy
