apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-green
  namespace: sandeep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: c1
        image: nginx
