apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v1
  namespace: sandeep
  annotations:
    kubernetes.io/change-cause: "nginx stable version"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: c1
        image: nginx
